# -*- coding: utf-8 -*-
"""speed_display.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8lUZUchForMW6RH14oRbj4yTaoQDuwB
"""

#display!!